package nginx

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// The fail2ban half of the HTTP side's protection (#141). nginx writes the
// misses (Guard.MissLog), the panel logs a failed login, and two jails read
// those logs and ban the address at the firewall.
//
// The ban has to land in front of the ports the front opens. THREEAX-IN,
// the chain nginx.ApplyFirewall hooks first into INPUT, only ever RETURNs or
// DROPs: 443 is let through by falling back into INPUT, where fail2ban's own
// chain — inserted into INPUT by its action — still gets its say, whichever of
// the two was inserted last. So the iptables actions work as they are, and on
// a machine without iptables fail2ban's nftables table hooks in on its own.

// Fail2banRoot is fail2ban's configuration directory. A variable so the tests
// can point it at a temporary tree.
var Fail2banRoot = "/etc/fail2ban"

// The files we own, relative to Fail2banRoot.
const (
	jailFile        = "jail.d/3ax-ui.conf"
	probeFilterFile = "filter.d/3ax-ui-probe.conf"
	loginFilterFile = "filter.d/3ax-ui-login.conf"
)

// jailHeader marks the files as ours, the same way header does nginx's:
// ApplyJails and RemoveJails leave a file without it alone.
const jailHeader = "# Generated by 3AX-UI. Do not edit: this file is rewritten whenever the\n" +
	"# front's protection is applied. Change a value in /etc/fail2ban/jail.local\n" +
	"# instead: fail2ban reads it after this file, and there it wins.\n"

// ErrNoFail2ban is a machine without fail2ban: the limits still hold, but
// nobody is banned. The panel says so on its Nginx page.
var ErrNoFail2ban = errors.New("fail2ban is not installed")

// Jails is what the two jails need to know.
type Jails struct {
	// MissLog is nginx's log of the misses (Guard.MissLog): the probe jail.
	MissLog string
	// LoginLog is the panel's own log, where a failed login names the
	// client: the login jail. Empty on a box, which has no login.
	LoginLog string
	// IgnoreIP are the addresses never banned — the guard's exemptions.
	// Loopback is always among them.
	IgnoreIP []string
	// BanAction is fail2ban's action; empty picks iptables-multiport where
	// iptables is, nftables-multiport elsewhere.
	BanAction string
}

// The bans (#141, owner's defaults): ten misses or five failed logins in ten
// minutes, an hour for a first ban, doubling for a repeat offender up to a
// day. Every one of them can be changed in jail.local.
const (
	probeMaxRetry = 10
	loginMaxRetry = 5
	findTime      = "10m"
	banTime       = "1h"
	banMaxTime    = "24h"
)

// render is every file of ours, by path relative to Fail2banRoot.
func (j Jails) render() map[string]string {
	action := j.BanAction
	if action == "" {
		action = defaultBanAction()
	}
	ignore := (&Guard{Exempt: j.IgnoreIP}).exemptList()
	// fail2ban spells loopback as a host with a mask.
	ignore[0] = "127.0.0.1/8"

	var b strings.Builder
	b.WriteString(jailHeader)
	b.WriteString("#\n# The front's protection (#141): addresses that probe the secret paths of\n")
	b.WriteString("# the HTTP side, or fail to log in to the panel, are banned from 80 and 443.\n")
	b.WriteString("# SSH stays open to them, so an owner who mistyped can still get in.\n")
	writeJail(&b, "3ax-ui-probe", j.MissLog, action, probeMaxRetry, ignore)
	files := map[string]string{probeFilterFile: probeFilter}
	if j.LoginLog != "" {
		writeJail(&b, "3ax-ui-login", j.LoginLog, action, loginMaxRetry, ignore)
		files[loginFilterFile] = loginFilter
	}
	files[jailFile] = b.String()
	return files
}

func writeJail(b *strings.Builder, name, logPath, action string, maxRetry int, ignore []string) {
	fmt.Fprintf(b, "\n[%s]\n", name)
	row := func(key, value string) { fmt.Fprintf(b, "%-17s = %s\n", key, value) }
	row("enabled", "true")
	// A file log, whatever backend the distro made the default: on Debian
	// 13 that is the journal, where nginx's log is not.
	row("backend", "auto")
	row("filter", name)
	row("logpath", logPath)
	row("port", "http,https")
	row("banaction", action)
	row("maxretry", fmt.Sprint(maxRetry))
	row("findtime", findTime)
	row("bantime", banTime)
	row("bantime.increment", "true")
	row("bantime.maxtime", banMaxTime)
	row("ignoreip", strings.Join(ignore, " "))
}

// probeFilter reads the miss log. fail2ban takes the date out of the line
// before matching, which leaves the brackets empty. The address is the first
// field, before anything a client sent, so no path can put another address
// there; nginx escapes a quote in the path in any case.
const probeFilter = jailHeader + `#
# The misses of the front's HTTP side (#141), as nginx writes them with
# log_format threeax_miss / threeax_limit:
#   198.51.100.7 [26/Sep/2026:21:54:29 +0000] miss "GET /base/panel/" 200
#   198.51.100.8 [26/Sep/2026:21:54:31 +0000] limit "POST /base/login" 405

[Definition]
failregex   = ^<HOST> \[\] (?:miss|limit) "
ignoreregex =
datepattern = ^[^\[]*\[({DATE})
`

// loginFilter reads the panel's log. The username and password in the line
// are HTML-escaped and kept on one line by the panel, so the only IP: "…"
// at the very end of it is the one the panel put there.
const loginFilter = jailHeader + `#
# Failed logins to the panel (#141), as the panel logs them — the address is
# the client's own, which nginx passes in X-Real-IP:
#   2026/09/26 21:54:29 WARNING - wrong username: "admin", password: "x", IP: "198.51.100.9"

[Definition]
failregex   = ^\s*WARNING - wrong username: .*, IP: "<HOST>"$
ignoreregex =
datepattern = {^LN-BEG}%%Y/%%m/%%d %%H:%%M:%%S
`

// defaultBanAction is the action that works with the firewall this machine
// has: the iptables one where our own firewall can live, nftables otherwise.
func defaultBanAction() string {
	if _, err := exec.LookPath("iptables"); err == nil {
		return "iptables-multiport"
	}
	return "nftables-multiport"
}

// fail2banControl is the running daemon. The tests replace it.
type fail2banControl interface {
	Running() bool
	Start() error
	Reload() error
}

var (
	fail2banCtl       fail2banControl = systemFail2ban{}
	fail2banInstalled                 = func() bool {
		_, err := exec.LookPath("fail2ban-client")
		return err == nil
	}
	// jailsRetryAfter holds back another start of a fail2ban that would
	// not start: the reconcile calls ApplyJails every half minute.
	jailsRetryAfter time.Time
)

// jailsRetryPause is how long a fail2ban that would not start is left alone,
// unless the jails change in the meantime.
const jailsRetryPause = 10 * time.Minute

// Fail2banInstalled reports whether fail2ban is on this machine.
func Fail2banInstalled() bool { return fail2banInstalled() }

// ApplyJails writes the jails and makes fail2ban run them: started if it is
// not running, reloaded if a file changed, left alone otherwise. The logs the
// jails read are created if they are not there yet — fail2ban refuses to
// start at all, sshd jail included, over a single missing log.
func ApplyJails(j Jails) error {
	if !fail2banInstalled() {
		return ErrNoFail2ban
	}
	for _, log := range []string{j.MissLog, j.LoginLog} {
		if log == "" {
			continue
		}
		if err := touch(log); err != nil {
			return err
		}
	}
	want := j.render()
	changed := false
	for _, rel := range []string{jailFile, probeFilterFile, loginFilterFile} {
		content, keep := want[rel]
		var fileChanged bool
		var err error
		if keep {
			fileChanged, err = writeOwned(filepath.Join(Fail2banRoot, rel), content)
		} else {
			fileChanged, err = removeOwned(filepath.Join(Fail2banRoot, rel))
		}
		if err != nil {
			return err
		}
		changed = changed || fileChanged
	}

	if !fail2banCtl.Running() {
		if !changed && time.Now().Before(jailsRetryAfter) {
			return nil
		}
		if err := fail2banCtl.Start(); err != nil {
			jailsRetryAfter = time.Now().Add(jailsRetryPause)
			return fmt.Errorf("start fail2ban: %w", err)
		}
		jailsRetryAfter = time.Time{}
		return nil
	}
	if changed {
		if err := fail2banCtl.Reload(); err != nil {
			return fmt.Errorf("reload fail2ban: %w", err)
		}
	}
	return nil
}

// RemoveJails takes our jails out again. fail2ban itself stays and keeps
// running: it may guard SSH or anything else the operator set it up for.
func RemoveJails() error {
	changed := false
	for _, rel := range []string{jailFile, probeFilterFile, loginFilterFile} {
		removed, err := removeOwned(filepath.Join(Fail2banRoot, rel))
		if err != nil {
			return err
		}
		changed = changed || removed
	}
	if changed && fail2banCtl.Running() {
		if err := fail2banCtl.Reload(); err != nil {
			return fmt.Errorf("reload fail2ban: %w", err)
		}
	}
	return nil
}

// writeOwned writes a file of ours, reporting whether it changed. A file by
// that name without our header is somebody else's and stays as it is.
func writeOwned(path, content string) (bool, error) {
	current, err := os.ReadFile(path)
	switch {
	case err == nil && string(current) == content:
		return false, nil
	case err == nil && !strings.HasPrefix(string(current), "# Generated by 3AX-UI."):
		return false, fmt.Errorf("%s is not ours (no 3AX-UI header): move it aside to let the panel manage it", path)
	case err != nil && !os.IsNotExist(err):
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// removeOwned removes a file of ours, reporting whether there was one.
func removeOwned(path string) (bool, error) {
	current, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !strings.HasPrefix(string(current), "# Generated by 3AX-UI.") {
		return false, nil
	}
	if err := os.Remove(path); err != nil {
		return false, err
	}
	return true, nil
}

// touch creates a log that is not there yet, leaving one that is untouched.
func touch(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o640)
	if err != nil {
		return err
	}
	return f.Close()
}

// systemFail2ban is the daemon on this machine, through systemd, OpenRC or
// fail2ban-client itself.
type systemFail2ban struct{}

func (systemFail2ban) Running() bool {
	if hasSystemd() {
		return exec.Command("systemctl", "is-active", "--quiet", "fail2ban").Run() == nil
	}
	return exec.Command("fail2ban-client", "ping").Run() == nil
}

func (systemFail2ban) Start() error {
	var cmd *exec.Cmd
	switch {
	case hasSystemd():
		// Enabled too: a box that reboots must come back with its bans.
		cmd = exec.Command("systemctl", "enable", "--now", "fail2ban")
	case commandExists("rc-service"):
		_ = exec.Command("rc-update", "add", "fail2ban").Run()
		cmd = exec.Command("rc-service", "fail2ban", "start")
	default:
		cmd = exec.Command("fail2ban-client", "start")
	}
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("%s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

func (systemFail2ban) Reload() error {
	if out, err := exec.Command("fail2ban-client", "reload").CombinedOutput(); err != nil {
		return fmt.Errorf("%s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

func commandExists(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}
